### ISSUE TITLE
Provide application administrators mechanism to provide custom headers

### ISSUE THREAD

**Issue by bbuechler** [asfadmin/thin-egress-app#145]
Patrick Quinn has requested we add `Cache-Control: private, max-age=600` header.

Rather than specially coding that one header, TEA should provide a configuration process that allows app admin to specify custom headers. 

Configuration could be a data redirect (global) config, or potentially a per-bucket setting similar  to defining PUBLIC/PRIVATE buckets.

**Comment by bilts** [comment]
Specifically, this is to support cases where a client needs to make many Range GET requests to the signed URL TEA returns.  This would be the case for any client doing partial file access.  GDAL, NetCDF / HDF5 (using FUSE mounts or similar), and OPeNDAP all do this. I am working on a Zarr implementation that will also need to do this.  Depending on how files are chunked, a single subset operation could commonly perform hundreds or more GET requests for smaller ranges of bytes against a single file.  The desire is to not have each of these requests go through TEA, but rather have the first request cache the Location it receives and subsequent requests use that location, both dramatically improving performance and decreasing cost / operational loads.

(Note: caching behavior of temporary redirects is not well specified, so some clients may benefit immediately while others may need updates).

The max age is negotiable, but should be some number below the actual expiration of the signed URL.  It should be long enough to serve a burst of small requests to the same URL for a single data operation, but it doesn't need to be more than a couple of minutes before needing to be refreshed.  The idea here is to prevent those hundreds of immediate follow-up requests from adding operational load, cost, and poor performance, not to allow indefinite reuse.

If this is somehow just an option, could we please make it the default?  It's a pretty big deal that it be set wherever possible for EOSDIS data.
