### ISSUE TITLE
Provide log messages for certain conditions for Cumulus

### ISSUE THREAD

**Issue by benbart** [asfadmin/thin-egress-app#165]
Request by Matt Savoie.

Cumulus' Elasticsearch / Kibana needs stable, robust log messages for successful and failed download attempts. 
### Success
Previously, success was determined by searching for `to_url`, probably this log message:
https://github.com/asfadmin/thin-egress-app/blob/2496a6e71f85c11508bee395f58354400b896d4e/lambda/app.py#L78

We need to provide a log message with a distinct code at time of success.

### Failure
Failure is determined by searching for `Could not download`, probably this log message: https://github.com/asfadmin/thin-egress-app/blob/2496a6e71f85c11508bee395f58354400b896d4e/lambda/app.py#L156

We need to provide a log message with a useful code in cases of failure.

These should be logged at `INFO` level or higher

**Comment by flamingbear** [comment]
Tagging myself as Matt Savoie here.

**Comment by bbuechler** [comment]
New log format is out.
