### ISSUE TITLE
Limit stack name to <= 38 chars

### ISSUE THREAD

**Issue by bbuechler** [asfadmin/thin-egress-app#230]
Instead of referencing `AWS::StackName` directly, figure out a way to use only the first ~35 characters to avoid name length issues (specifically with `UpdatePolicyLambdaIamRole`). 

https://github.com/asfadmin/thin-egress-app/blob/2b3bb4d339657b38797f0c841f8c2d5a86061735/cloudformation/thin-egress-app.yaml#L278

**Comment by benbart** [comment]
I've figured out a way to trim the string that involves creating a lambda to do so. If we want to create a lambda just for that, I'll go ahead.
