### ISSUE TITLE
Make Lambda memory allocation dynamic, default to 1,792 MB

### ISSUE THREAD

**Issue by bbuechler** [asfadmin/thin-egress-app#260]
We seen testing at scale that normal usage is closer to 400MB, but spikes to near 700MB. However, at 1792 MB, we can allocate an entire vCPU to help mitigate backgrounding. 

1792MB seems a little on the excessive side when normal usage is around 400 and spikes only go up to 700, however Lambda only charges you for RAM used, not RAM allocated. Getting that full proportional vCPU should offset any concerns of wasted RAM.

We should add a new Parameter to the CF & TF to support dynamic setting of the Lambda Memory allocation, and have it default to 1792. 

https://docs.aws.amazon.com/lambda/latest/dg/configuration-console.html#:~:text=AT%201%2C792%20MB%2C%20a%20function%20has%20the%20equivalent%20of%20one%20full%20vCPU

**Comment by benbart** [comment]
This was implemented with PR #261
