### ISSUE TITLE
Explore using semantic version ID's instead of the current numerical series. 

### ISSUE THREAD

**Issue by bbuechler** [asfadmin/thin-egress-app#353]
How might we inject a semantic version id into the build process? Trigger release from a `v#.#.#` tag (like our cirrus builds) and inject the tag name into the code instead of `build.#` value? Alternatively, accept a build version id as a jenkins build param?

Do we rely on `build.#` syntax in the release code anywhere?

**Comment by reweeden** [comment]
The GitHub actions build takes version numbers from release tags. Currently it uses a format compatible with the conventions that tags had before: `some-prefix.<version>`, so for semver we just create tags named like `some-prefix.x.x.x`

See #459
