### ISSUE TITLE
UpdatePolicyLambda timeouts during CloudFormation stack creation

### ISSUE THREAD

**Issue by philvarner** [asfadmin/thin-egress-app#388]
This is deployed to us-west-2. It is part of a deployment of https://github.com/nasa/cumulus using TEA version 102.

We have not deployed this to us-west-2, but it worked when deploying to us-east-1 in April. Deployment to us-east-1 no longer works because of #386 

The CloudFormation stack fails creation with these relevant events (in chronological order) for the TriggerInRegionCIDRUpdate component:

(1)
```
CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [05d47ac7-1b99-45b0-8353-246973729264]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.
```

(2)
```
The following resource(s) failed to create: [TriggerInRegionCIDRUpdate]. Rollback requested by user.
```

(3)
```
CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [8b32a2cb-57a4-4f0c-a192-72c298050321]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.
```

(4)
```
The following resource(s) failed to delete: [TriggerInRegionCIDRUpdate]. 
```

In the logs for the TriggerInRegionCIDRUpdate lambda, this appears to be the problem:

```
START ...
Current reigon in us-west-2
END ...
Task timed out after 6.01 seconds
```

There are no other log messages around this.

**Comment by bbuechler** [comment]
We've seen other process, inside private VPC's, periodically timeout making what would be a near-instant request to fetch IP CIDR json file. I suspect that is what you saw.

**Comment by philvarner** [comment]
Good to know, I suspected either that or the IAM update request was taking a while from us-west-2. I'm trying it again with a larger timeout.

**Comment by philvarner** [comment]
I set the timeout to 30s (the largest value allowed by the schema) and it still timeouts.

**Comment by philvarner** [comment]
I think this may be being caused by incorrectly-configured network infrastructure. Investigating further now.

**Comment by philvarner** [comment]
After further investigation, this was happening because I was deploying into a subnet that was directly connected to an Internet Gateway, instead of going through a NAT, which I know now that Lambdas have to use. This is what the existing deployment in us-east-1 was doing, but us-west-2 wasn't setup in the same way. 

So, maybe this is just something to note in Troubleshooting.

However, now I'm getting this problem with the deploy trying to invoke the tea_map_cache and not being able to resolve the (private) API Gateway URL.

```
module.cumulus.module.distribution.data.aws_lambda_invocation.tea_map_cache: Still reading... [40s elapsed]

Error: Lambda function (xxx-phil0-TeaCache) returned error: ({"errorType":"RequestError","errorMessage":"getaddrinfo ENOTFOUND d5xt0v9zf0.execute-api.us-west-2.amazonaws.com","trace":["RequestError: getaddrinfo ENOTFOUND d5xt0v9zf0.execute-api.us-west-2.amazonaws.com","    at ClientRequest.<anonymous> (/var/task/node_modules/got/dist/source/core/index.js:956:111)","    at Object.onceWrapper (events.js:421:26)","    at ClientRequest.emit (events.js:326:22)","    at ClientRequest.EventEmitter.emit (domain.js:483:12)","    at ClientRequest.origin.emit (/var/task/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)","    at TLSSocket.socketErrorListener (_http_client.js:427:9)","    at TLSSocket.emit (events.js:314:20)","    at TLSSocket.EventEmitter.emit (domain.js:483:12)","    at emitErrorNT (internal/streams/destroy.js:92:8)","    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)","    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)"]})
```

**Comment by philvarner** [comment]
For that issue, there was no Endpoint defined for the public subnet, so I can now resolve the API url. However, tea_map_cache is timing now, so I think there's a connectivity issue now.

Anyway, closing this issue, as the original problem has been resolved.
