### ISSUE TITLE
Update packaging documentation to reflect code refactoring

### ISSUE THREAD

**Issue by bbuechler** [asfadmin/thin-egress-app#46]
In the README.md, we're currently advising users who want to package the data to zip up ONLY the top level `.py` files, which miss the `common/*.py modules`. 

https://github.com/asfadmin/thin-egress-app/blame/devel/README.MD#L52

**Comment by benbart** [comment]
I've fixed this issue with this PR: https://github.com/asfadmin/thin-egress-app/pull/47
